# Generated by Django 4.0.1 on 2022-05-11 08:40

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'unique': 'Такой логин уже существует'}, max_length=150, unique=True, verbose_name='Логин')),
                ('first_name', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, null=True, verbose_name='Фамилия')),
                ('otchestvo', models.CharField(max_length=100, null=True, verbose_name='Отчество')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('number', models.CharField(max_length=50, null=True, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Адрес')),
                ('is_student', models.BooleanField(default=False, verbose_name='Студент')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='Учитель')),
                ('image', models.ImageField(blank=True, upload_to='uploads/accounts/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя курса')),
                ('steps', models.SmallIntegerField(default=10, verbose_name='Длительность курса в уроках')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
            bases=('univerapp.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
            bases=('univerapp.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_send_message', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата отправки')),
                ('date_read_message', models.DateTimeField(null=True, verbose_name='Дата прочитания')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('receiver_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_user', to=settings.AUTH_USER_MODEL)),
                ('send_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_send_message', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_materials', to='univerapp.course')),
                ('receiver_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_receiver_user', to=settings.AUTH_USER_MODEL)),
                ('send_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_send_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Обучающий материал',
                'verbose_name_plural': 'Обучающий материалы',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.ManyToManyField(related_name='student_course', to='univerapp.Course'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='HomeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_send_task', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hometask_materials', to='univerapp.course')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hometask_receiver_user', to='univerapp.student')),
                ('teacher', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hometask_send_user', to='univerapp.teacher')),
            ],
            options={
                'verbose_name': 'Обучающий материал',
                'verbose_name_plural': 'Обучающий материалы',
            },
        ),
    ]
