# Generated by Django 4.0.1 on 2022-05-24 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univerapp', '0002_remove_material_send_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometask',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hometask_send_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
