# Generated by Django 4.0.1 on 2022-06-10 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univerapp', '0004_alter_hometask_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometask',
            name='exec_file',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Файл ответа'),
        ),
        migrations.AlterField(
            model_name='hometask',
            name='is_exec',
            field=models.BooleanField(default=False, verbose_name='Аткарылды'),
        ),
        migrations.AlterField(
            model_name='hometask',
            name='status',
            field=models.CharField(default='Жооп күтүүдө', max_length=60, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='HomeTaskMixing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_send_task', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univerapp.course')),
            ],
        ),
    ]
