# Generated by Django 3.2.4 on 2022-06-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univerapp', '0005_alter_hometask_exec_file_alter_hometask_is_exec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometask',
            name='exec_file',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Жооп файл'),
        ),
    ]
