# Generated by Django 4.0.1 on 2022-05-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univerapp', '0010_course_teacher_dialog_last_message_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date_read_message',
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
