# Generated by Django 4.0.1 on 2022-05-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univerapp', '0012_alter_message_receiver_user_alter_message_send_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(to='univerapp.Course'),
        ),
    ]
