# Generated by Django 4.0.1 on 2022-05-18 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univerapp', '0016_alter_user_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='courses',
        ),
    ]
