# Generated by Django 4.0.1 on 2022-05-21 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univerapp', '0017_remove_user_courses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hometask',
            options={'verbose_name': 'Тапшырма', 'verbose_name_plural': 'Тапшырмалар'},
        ),
        migrations.AddField(
            model_name='hometask',
            name='exec_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hometask',
            name='exec_file',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='hometask',
            name='is_exec',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hometask',
            name='status',
            field=models.CharField(default='ожидает ответа', max_length=60, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='hometask',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hometask_receiver_user', to='univerapp.student'),
        ),
        migrations.AlterField(
            model_name='hometask',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hometask_send_user', to='univerapp.teacher'),
        ),
    ]
